"""Add StationReview model back

Revision ID: 80832b8b5d2b
Revises: a96d562fb1d4
Create Date: 2026-09-28 10:31:19.038667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80832b8b5d2b'
down_revision: Union[str, Sequence[str], None] = 'a96d562fb1d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('station_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_reviews_id'), 'station_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_station_reviews_station_id'), 'station_reviews', ['station_id'], unique=False)
    op.create_index(op.f('ix_station_reviews_user_id'), 'station_reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_station_reviews_user_id'), table_name='station_reviews')
    op.drop_index(op.f('ix_station_reviews_station_id'), table_name='station_reviews')
    op.drop_index(op.f('ix_station_reviews_id'), table_name='station_reviews')
    op.drop_table('station_reviews')
    # ### end Alembic commands ###
