"""Initial setup

Revision ID: a96d562fb1d4
Revises: 
Create Date: 2026-09-28 09:57:29.104285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a96d562fb1d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_station_reviews_id'), table_name='station_reviews')
    op.drop_index(op.f('ix_station_reviews_station_id'), table_name='station_reviews')
    op.drop_index(op.f('ix_station_reviews_user_id'), table_name='station_reviews')
    op.drop_table('station_reviews')
    op.create_index(op.f('ix_station_sockets_id'), 'station_sockets', ['id'], unique=False)
    op.drop_constraint(op.f('stations_station_code_key'), 'stations', type_='unique')
    op.create_index(op.f('ix_stations_id'), 'stations', ['id'], unique=False)
    op.create_index(op.f('ix_stations_name'), 'stations', ['name'], unique=False)
    op.create_index(op.f('ix_stations_station_code'), 'stations', ['station_code'], unique=True)
    op.drop_index(op.f('ix_users_city'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_constraint(op.f('users_phone_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_phone_key'), 'users', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_city'), 'users', ['city'], unique=False)
    op.drop_index(op.f('ix_stations_station_code'), table_name='stations')
    op.drop_index(op.f('ix_stations_name'), table_name='stations')
    op.drop_index(op.f('ix_stations_id'), table_name='stations')
    op.create_unique_constraint(op.f('stations_station_code_key'), 'stations', ['station_code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_station_sockets_id'), table_name='station_sockets')
    op.create_table('station_reviews',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('station_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_anonymous', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('station_reviews_station_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('station_reviews_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('station_reviews_pkey'))
    )
    op.create_index(op.f('ix_station_reviews_user_id'), 'station_reviews', ['user_id'], unique=False)
    op.create_index(op.f('ix_station_reviews_station_id'), 'station_reviews', ['station_id'], unique=False)
    op.create_index(op.f('ix_station_reviews_id'), 'station_reviews', ['id'], unique=False)
    # ### end Alembic commands ###
